### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by davidcornu**
Bumps the version to `3.0.0` and adds a `CHANGELOG.md` file.

### CODE REVIEW

**Comment by davidcornu** [comment]
Not sure what else needs to be done to get this pushed to NPM

**Comment by chrisberthe** [comment]
I'm not too sure what the setup process is for Shipit but this needs to be integrated. I know this was done previously for both the https://github.com/Shopify/slate/ and https://github.com/Shopify/theme-scripts/ repositories.

I don't have time this week to look into Shipit, so I think for the time being we can have someone with admin privileges push to NPM directly. @antoinegrant? 😬

**Comment by davidcornu** [comment]
Need to add https://github.com/Shopify/theme-lint/issues/31 to the CHANGELOG

**Comment by davidcornu** [comment]
Rebased and added an entry for #31.

**Comment by davidcornu** [comment]
Shipped https://www.npmjs.com/package/@shopify/theme-lint/v/3.0.0.

**Pull request merged**
