### PR TITLE
Adopt Prettier

### PR DESCRIPTION
**Pull request by davidcornu**
Adopt https://github.com/prettier/prettier and run it on CI.

**Changes**
- Added `npm run prettier-check` that outputs any differences with the expected format
- Added `npm run prettier` that rewrites files with prettier
- Updated `circle.yml` to run `npm run prettier-check`
- Ran `npm run prettier` over the code and committed the change

### CODE REVIEW

**Comment by chrisberthe** [comment]
Merged #20 - mind fixing the conflicts before review?

**Comment by davidcornu** [comment]
@chrisberthe done

**Comment by chrisberthe** [comment]
Looks good on my side 🎩👍.

**Comment by davidcornu** [comment]
I also updated the contributing doc https://github.com/Shopify/theme-lint/commit/ddb21067788027636209728b2a5ee3b8c78caec1.

**Pull request merged**
